/**
 * index.tsx
 * ---------
 * Entry point for the Worker Scheduling Manager React application.
 *
 * - Renders the <App /> component into the root DOM node.
 * - Wraps the app in React.StrictMode for highlighting potential problems.
 * - Imports global CSS styles.
 *
 * This file is generated by Create React App and is rarely modified except for custom bootstrapping.
 */
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
